name: Python Notebook CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-notebook:
    runs-on: windows-latest

    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v4

    # 设置 Python 环境
    - name: Setup Python 3.9.18
      uses: actions/setup-python@v4
      with:
        python-version: 3.9.18

    # 安装依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 运行 Jupyter Notebook
    - name: Execute Jupyter Notebook
      run: |
        pip install notebook nbconvert  # 确保 Jupyter 和 nbconvert 已安装
        jupyter nbconvert --to notebook --execute --inplace DRL_v2.ipynb

    # 上传 Notebook 执行结果（可选）
    - name: Upload executed notebook
      uses: actions/upload-artifact@v3
      with:
        name: executed-notebook
        path: DRL_v2.ipynb
